#This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

# For deployment, it will be necessary to create a PyPI API token and store it as a secret
# https://docs.github.com/en/actions/reference/encrypted-secrets

name: Python package

on:
  push:
    branches: [ main, develop ]
    tags: [ '*' ]
  pull_request:
    branches: [ main, develop ]
  repository_dispatch:
    types: [create-release]

jobs:

  nipype-conv:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Revert version to most recent tag on upstream update
      if: github.event_name == 'repository_dispatch'
      run: git checkout $(git tag -l | tail -n 1 | awk -F post '{print $1}')    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
    - name: Install build dependencies
      run: python -m pip install --upgrade pip
    - name: Install requirements
      run: python -m pip install -r ./nipype-auto-conv/requirements.txt
    - name: Run automatic Nipype > Pydra conversion
      run: ./nipype-auto-conv/generate
    - uses: actions/upload-artifact@v3
      with:
        name: converted-nipype
        path: pydra/tasks/CHANGEME/auto

  devcheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.11']  # Check oldest and newest versions
        pip-flags: ['', '--editable']
        pydra:
        - 'pydra'
        - '--editable git+https://github.com/nipype/pydra.git#egg=pydra'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Revert version to most recent tag on upstream update
      if: github.event_name == 'repository_dispatch'
      run: git checkout $(git tag -l | tail -n 1 | awk -F post '{print $1}')    
    - name: Download tasks converted from Nipype 
      uses: actions/download-artifact@v3
      with:
        name: converted-nipype
        path: pydra/tasks/CHANGEME/auto
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install Pydra
      run: |
        pip install ${{ matrix.pydra }}
        python -c "import pydra as m; print(f'{m.__name__} {m.__version__} @ {m.__file__}')"
    - name: Install task package
      run: |
        pip install ${{ matrix.pip-flags }} ".[dev]"
        python -c "import pydra.tasks.CHANGEME as m; print(f'{m.__name__} {m.__version__} @ {m.__file__}')"
        python -c "import pydra as m; print(f'{m.__name__} {m.__version__} @ {m.__file__}')"

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.11']

    steps:
    - uses: actions/checkout@v3
    - name: Revert version to most recent tag on upstream update
      if: github.event_name == 'repository_dispatch'
      run: git checkout $(git tag -l | tail -n 1 | awk -F post '{print $1}')
    - name: Download tasks converted from Nipype 
      uses: actions/download-artifact@v3
      with:
        name: converted-nipype
        path: pydra/tasks/CHANGEME/auto
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install task package
      run: |
        pip install ".[test]"
        python -c "import pydra.tasks.CHANGEME as m; print(f'{m.__name__} {m.__version__} @ {m.__file__}')"
        python -c "import pydra as m; print(f'{m.__name__} {m.__version__} @ {m.__file__}')"
    - name: Test with pytest
      run: |
        pytest -sv --doctest-modules pydra/tasks/CHANGEME \
            --cov pydra.tasks.CHANGEME --cov-report xml
    - uses: codecov/codecov-action@v3
      if: ${{ always() }}

  deploy:
    needs: [devcheck, test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Download tasks converted from Nipype 
      uses: actions/download-artifact@v3
      with:
        name: converted-nipype
        path: pydra/tasks/CHANGEME/auto
    - name: Tag release with a post-release based on Nipype and Nipype2Pydra versions
      if: github.event_name == 'repository_dispatch'
      run: |
        TAG=$(git tag -l | tail -n 1 | awk -F post '{print $1}')
        POST=$(python -c "from pydra.tasks.CHANGEME.auto._version import *; print(post_release)")
        git checkout $TAG
        git add -f pydra/tasks/CHANGEME/auto/_version.py
        git commit -am"added auto-generated version to make new tag for package version"
        git tag ${TAG}post${POST}    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install build tools
      run: python -m pip install build twine
    - name: Build source and wheel distributions
      run: python -m build
    - name: Check distributions
      run: twine check dist/*
    - uses: actions/upload-artifact@v3
      with:
        name: distributions
        path: dist/
    # Deploy on tags if PYPI_API_TOKEN is defined in the repository secrets.
    # Secrets are not accessible in the if: condition [0], so set an output variable [1]
    # [0] https://github.community/t/16928
    # [1] https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter
    - name: Check for PyPI token on tag
      id: deployable
      if: (github.event_name == 'push' && startsWith(github.ref, 'refs/tags')) || github.event_name == 'repository_dispatch'
      env:
        PYPI_API_TOKEN: "${{ secrets.PYPI_API_TOKEN }}"
      run: if [ -n "$PYPI_API_TOKEN" ]; then echo "DEPLOY=true" >> $GITHUB_OUTPUT; fi
    - name: Upload to PyPI
      if: steps.deployable.outputs.DEPLOY
      uses: pypa/gh-action-pypi-publish@v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
