name: Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.11"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Install Ubuntu packaging
      run: sudo apt update && sudo apt install -y python3-packaging

    - uses: actions/checkout@v2

    - name: Unset header
      # checkout@v2 adds a header that makes branch protection report errors
      # because the Github action bot is not a collaborator on the repo
      run: git config --local --unset http.https://github.com/.extraheader

    - name: Fetch tags
      run: git fetch --prune --unshallow

    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Update build tools
      run: python3 -m pip install --upgrade pip build

    - name: Install required file-formats packages
      run: |
        pushd required-fileformats
        python3 -m pip install -r requirements.txt
        popd

    - name: Install Package
      run: python3 -m pip install -e .[test]

    - name: Pytest
      run: pytest -vvs --cov nipype2pydra --cov-config .coveragerc --cov-report xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
