name: Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.11"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - name: Disable etelemetry
      run:  echo "NO_ET=TRUE" >> $GITHUB_ENV

    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Update build tools
      run: python -m pip install --upgrade pip

    - name: Install required file-formats packages
      run: |
        pushd required-fileformats
        python -m pip install -r requirements.txt
        popd

    - name: Install Package
      run: python -m pip install -e .[test]

    - name: Pytest
      run: pytest -vvs --cov nipype2pydra --cov-config .coveragerc --cov-report xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
